# Run code generator and open PR if new change available.
#
# There is no stability guarantee for this workflow, since it's supposed to only be
# used in infra managed by us.
#
# Note: We also call this workflow from tidy.yml.
#
# Usage:
#
# ```yml
#   docs:
#     uses: taiki-e/github-actions/.github/workflows/gen.yml@main
# ```
#
# See "on.workflow_call.inputs" below for input options.

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      script:
        required: false
        type: string
        default: tools/gen.sh
      commit-script:
        required: false
        type: string
        default: tools/ci/gen.sh
      title:
        required: false
        type: string
        default: Update generated code
      branch:
        required: false
        type: string
        default: update-generated-code
      install-rust:
        required: false
        type: boolean
        default: false
      rust:
        required: false
        type: string
        default: nightly
      automerge:
        required: false
        type: boolean
        default: false
      free-device-space:
        required: false
        type: boolean
        default: false

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
  # Reusable workflows cannot inherit environment variables.
  ATOMIC_MAYBE_UNINIT_DENY_WARNINGS: 1
  CARGO_HACK_DENY_WARNINGS: 1
  CARGO_LLVM_COV_DENY_WARNINGS: 1
  CARGO_MINIMAL_VERSIONS_DENY_WARNINGS: 1
  CARGO_NO_DEV_DEPS_DENY_WARNINGS: 1
  CONST_FN_DENY_WARNINGS: 1
  PORTABLE_ATOMIC_DENY_WARNINGS: 1
  SEMIHOSTING_DENY_WARNINGS: 1

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  gen:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      pull-requests: write # for gh pr edit --add-assignee / gh pr review --approve
      repository-projects: read # for gh pr edit --add-assignee
    steps:
      - uses: taiki-e/checkout-action@v1
      - uses: taiki-e/github-actions/free-device-space@main
        if: inputs.free-device-space
      - uses: taiki-e/github-actions/install-rust@main
        with:
          toolchain: ${{ inputs.rust }}
        if: inputs.install-rust
      - id: run
        run: |
          bash "${SCRIPT}"
          if [[ -e "${COMMIT_SCRIPT}" ]]; then
            printf 'commit=true\n' >>"${GITHUB_OUTPUT}"
          fi
        env:
          SCRIPT: ${{ inputs.script }}
          COMMIT_SCRIPT: ${{ inputs.commit-script }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Handle diff
        id: diff
        run: bash "${COMMIT_SCRIPT}"
        env:
          COMMIT_SCRIPT: ${{ inputs.commit-script }}
        if: (inputs.automerge || steps.run.outputs.commit == 'true') && github.repository_owner == 'taiki-e' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' && github.ref == 'refs/heads/main')
      - run: git add -N . && git -c color.ui=always diff --exit-code
      - id: create-pull-request
        uses: peter-evans/create-pull-request@v8
        with:
          title: ${{ inputs.title }}
          body: |
            Auto-generated by CI using [create-pull-request](https://github.com/peter-evans/create-pull-request).

            This will be auto-merged when CI has passed because this is an auto-generated PR in a defined format and is usually considered no additional review is required.
          branch: ${{ inputs.branch }}
          token: ${{ secrets.CREATE_PR_TOKEN }}
        if: (inputs.automerge || steps.run.outputs.codegen-commit == 'true') && github.repository_owner == 'taiki-e' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' && github.ref == 'refs/heads/main') && steps.diff.outputs.success == 'false'
      - name: Notify PR author by assigning PR
        run: gh pr edit --add-assignee taiki-e "${PR_NUMBER:?}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.create-pull-request.outputs.pull-request-number }}
        if: (!inputs.automerge) && steps.run.outputs.codegen-commit == 'true' && github.repository_owner == 'taiki-e' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' && github.ref == 'refs/heads/main') && steps.diff.outputs.success == 'false'
      - name: Enable auto-merge for auto-generated PR
        run: gh pr merge --rebase --auto "${PR_NUMBER:?}"
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_PR_TOKEN }}
          PR_NUMBER: ${{ steps.create-pull-request.outputs.pull-request-number }}
        if: inputs.automerge && github.repository_owner == 'taiki-e' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' && github.ref == 'refs/heads/main') && steps.diff.outputs.success == 'false' && steps.create-pull-request.outputs.pull-request-operation == 'created'
      - name: Approve auto-generated PR for auto-merge
        run: gh pr review --approve "${PR_NUMBER:?}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.create-pull-request.outputs.pull-request-number }}
        if: inputs.automerge && github.repository_owner == 'taiki-e' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' && github.ref == 'refs/heads/main') && steps.diff.outputs.success == 'false' && (steps.create-pull-request.outputs.pull-request-operation == 'created' || steps.create-pull-request.outputs.pull-request-operation == 'updated')
